### ISSUE TITLE
Dwarven Village [Deliveryman] Rogin 

### ISSUE THREAD

**Issue by Sacrifice78** [L2JGeo/L2J_Geodata#10]
NpcId=31363 are static and cant move.

**Comment by maneco2** [comment]
I have checked this a long time ago, please send me print screen.

**Comment by maneco2** [comment]
Need fix this in core server.

**Comment by Sacrifice78** [comment]
Okey @maneco2, yes true, as you told this issue happend on other locations. We hope that @HorridoJoho fix and stabilize geoengine soon. Many problems of this type would be over. Thanks @maneco2 for take a look :+1:
