### ISSUE TITLE
[C4] Missing region 24_13

### ISSUE THREAD

**Issue by zarie** [L2JGeo/L2J_Geodata#19]

**Comment by maneco2** [comment]
You checked retail maps in C:\Program Files (x86)\Lineage II\C4\maps???? And all  your others report of missing region?

**Comment by zarie** [comment]
It's not so easy. I saw them in geo pack for l20ff C4 (but... can we trust them?), and in config files in different servers. Therefore, I ask.

But maybe it's good idea to base on /maps/*.unr - only.
It's not urgent case, but it's good idea to check it out.

**Comment by maneco2** [comment]
Yes it can be based on /mapas/*.unr
