### ISSUE TITLE
Devastated castle

### ISSUE THREAD

**Issue by valanths1990** [L2JGeo/L2J_Geodata#8]
.Hello there i found some missing geodata blocks
in devasted conq hall

for exmaple in bridge when enter and on the left side where archers stand

PS> thank you for your good work :)

**Comment by maneco2** [comment]
The character is skating on the bridge, right?

**Comment by valanths1990** [comment]
This is one place on the bridge
http://prntscr.com/bj11p3

and inside
http://prntscr.com/bj12ci

if i find more i will let you know :)

**Comment by maneco2** [comment]
Fixed in https://github.com/L2JGeo/L2J_Geodata/commit/921417802717ee57ca74028f808192586f12eabc Thanks.

**Comment by maneco2** [comment]
Fixed in https://github.com/L2JGeo/L2J_Geodata/commit/921417802717ee57ca74028f808192586f12eabc Thanks.
